module.exports = {
	id: 1,
	email: 'nikolaos@meeshkan.com',
	username: 'k4m4',
	selectedRepos: [
		'active-onions',
		'binary-cli',
		'bitcoincash-regex',
		'btc-balance.now',
		'caesar-cli',
		'cf-detect.now',
		'cloudflare-detect',
		'cryptaddress-validator',
		'cryptaddress.now',
		'cryptocurrency-address-detector',
		'dash-regex',
		'dcipher',
		'dcipher-cli',
		'dogecoin-regex',
		'donations',
		'dymerge',
		'esolangs',
		'esolangs-cli',
		'ethereum-regex',
		'ghost-detect',
		'ghost-detect.now',
		'ghost-version',
		'hash-detector',
		'hash-detector-cli',
		'hash-length-regex',
		'hex-cli',
		'instaprof-site',
		'isitup.now',
		'kickthemout',
		'lexis-cli',
		'lexis-count',
		'lexis.now',
		'litecoin-regex',
		'md5-regex',
		'monero-regex',
		'movies-for-hackers',
		'neo-regex',
		'now-name',
		'now-name-cli',
		'onioff',
		'onion-regex',
		'ripemd-regex',
		'ripple-regex',
		'sha-regex',
		'terminals-are-sexy',
		'tor-detect',
		'tor-detect.now',
		'url-cli'
	]
};
