module.exports = {
	id: '8945656',
	displayName: 'Nikolaos Kamarinakis',
	username: 'k4m4',
	profileUrl: 'https://github.com/k4m4',
	photos: [{ value: 'https://avatars1.githubusercontent.com/u/8945656?v=4' }],
	provider: 'github',
	_raw: '{"login":"k4m4","id":8945656,"node_id":"MDQ6VXNlcjg5NDU2NTY=","avatar_url":"https://avatars1.githubusercontent.com/u/8945656?v=4","gravatar_id":"","url":"https://api.github.com/users/k4m4","html_url":"https://github.com/k4m4","followers_url":"https://api.github.com/users/k4m4/followers","following_url":"https://api.github.com/users/k4m4/following{/other_user}","gists_url":"https://api.github.com/users/k4m4/gists{/gist_id}","starred_url":"https://api.github.com/users/k4m4/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/k4m4/subscriptions","organizations_url":"https://api.github.com/users/k4m4/orgs","repos_url":"https://api.github.com/users/k4m4/repos","events_url":"https://api.github.com/users/k4m4/events{/privacy}","received_events_url":"https://api.github.com/users/k4m4/received_events","type":"User","site_admin":false,"name":"Nikolaos Kamarinakis","company":"University of Maryland","blog":"https://nikolaskama.me/","location":"College Park, Maryland","email":null,"hireable":null,"bio":"Into Node.js, these days.","public_repos":58,"public_gists":3,"followers":965,"following":54,"created_at":"2014-09-28T08:08:27Z","updated_at":"2020-02-24T17:01:03Z"}',
	_json: {
		login: 'k4m4',
		id: 8945656,
		node_id: 'MDQ6VXNlcjg5NDU2NTY=',
		avatar_url: 'https://avatars1.githubusercontent.com/u/8945656?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/k4m4',
		html_url: 'https://github.com/k4m4',
		followers_url: 'https://api.github.com/users/k4m4/followers',
		following_url: 'https://api.github.com/users/k4m4/following{/other_user}',
		gists_url: 'https://api.github.com/users/k4m4/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/k4m4/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/k4m4/subscriptions',
		organizations_url: 'https://api.github.com/users/k4m4/orgs',
		repos_url: 'https://api.github.com/users/k4m4/repos',
		events_url: 'https://api.github.com/users/k4m4/events{/privacy}',
		received_events_url: 'https://api.github.com/users/k4m4/received_events',
		type: 'User',
		site_admin: false,
		name: 'Nikolaos Kamarinakis',
		company: 'University of Maryland',
		blog: 'https://nikolaskama.me/',
		location: 'College Park, Maryland',
		email: null,
		hireable: null,
		bio: 'Into Node.js, these days.',
		public_repos: 58,
		public_gists: 3,
		followers: 965,
		following: 54,
		created_at: '2014-09-28T08:08:27Z',
		updated_at: '2020-02-24T17:01:03Z',
	},
};
