module.exports = [
	{ name: 'active-onions', stars: 3, forks: 1 },
	{ name: 'binary-cli', stars: 4, forks: 3 },
	{ name: 'bitcoincash-regex', stars: 4, forks: 0 },
	{ name: 'btc-balance.now', stars: 2, forks: 2 },
	{ name: 'caesar-cli', stars: 11, forks: 1 },
	{ name: 'cf-detect.now', stars: 3, forks: 1 },
	{ name: 'cloudflare-detect', stars: 11, forks: 3 },
	{ name: 'cryptaddress-validator', stars: 71, forks: 6 },
	{ name: 'cryptaddress.now', stars: 15, forks: 3 },
	{
		name: 'cryptocurrency-address-detector',
		stars: 23,
		forks: 2
	},
	{ name: 'dash-regex', stars: 3, forks: 0 },
	{ name: 'dcipher', stars: 87, forks: 22 },
	{ name: 'dcipher-cli', stars: 164, forks: 21 },
	{ name: 'dogecoin-regex', stars: 4, forks: 0 },
	{ name: 'donations', stars: 51, forks: 18 },
	{ name: 'dymerge', stars: 155, forks: 40 },
	{ name: 'esolangs', stars: 6, forks: 0 },
	{ name: 'esolangs-cli', stars: 0, forks: 1 },
	{ name: 'ethereum-regex', stars: 11, forks: 0 },
	{ name: 'ghost-detect', stars: 4, forks: 1 },
	{ name: 'ghost-detect.now', stars: 2, forks: 2 },
	{ name: 'ghost-version', stars: 2, forks: 0 },
	{ name: 'hash-detector', stars: 7, forks: 3 },
	{ name: 'hash-detector-cli', stars: 5, forks: 3 },
	{ name: 'hash-length-regex', stars: 3, forks: 1 },
	{ name: 'hex-cli', stars: 6, forks: 3 },
	{ name: 'instaprof-site', stars: 3, forks: 1 },
	{ name: 'isitup.now', stars: 12, forks: 3 },
	{ name: 'kickthemout', stars: 1621, forks: 372 },
	{ name: 'lexis-cli', stars: 3, forks: 0 },
	{ name: 'lexis-count', stars: 2, forks: 1 },
	{ name: 'lexis.now', stars: 2, forks: 2 },
	{ name: 'litecoin-regex', stars: 4, forks: 1 },
	{ name: 'md5-regex', stars: 4, forks: 1 },
	{ name: 'monero-regex', stars: 5, forks: 0 },
	{
		name: 'movies-for-hackers',
		stars: 7974,
		forks: 740
	},
	{ name: 'neo-regex', stars: 2, forks: 0 },
	{ name: 'nephthys', stars: 7, forks: 0 },
	{ name: 'now-name', stars: 0, forks: 0 },
	{ name: 'now-name-cli', stars: 0, forks: 0 },
	{ name: 'onioff', stars: 384, forks: 100 },
	{ name: 'onion-regex', stars: 8, forks: 4 },
	{ name: 'open-anyway', stars: 5, forks: 0 },
	{ name: 'open-anyway-cli', stars: 4, forks: 0 },
	{ name: 'ripemd-regex', stars: 2, forks: 0 },
	{ name: 'ripple-regex', stars: 3, forks: 0 },
	{ name: 'sha-regex', stars: 4, forks: 1 },
	{
		name: 'terminals-are-sexy',
		stars: 8898,
		forks: 484
	},
	{ name: 'tor-detect', stars: 12, forks: 3 },
	{ name: 'tor-detect.now', stars: 5, forks: 3 },
	{ name: 'url-cli', stars: 3, forks: 4 }
];
