module.exports = [
	{
		name: 'active-onions',
		stars: { latest: 3, difference: 1 },
		forks: { latest: 1, difference: 0 },
		views: { latest: 1, difference: 0 },
		clones: { latest: 10, difference: 0 },
	},
	{
		name: 'binary-cli',
		stars: { latest: 4, difference: 1 },
		forks: { latest: 3, difference: 0 },
		views: { latest: 4, difference: -2 },
		clones: { latest: 4, difference: 2 },
	},
	{
		name: 'bitcoincash-regex',
		stars: { latest: 4, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 41, difference: 14 },
		clones: { latest: 8, difference: 4 },
	},
	{
		name: 'btc-balance.now',
		stars: { latest: 2, difference: -1 },
		forks: { latest: 2, difference: 0 },
		views: { latest: 3, difference: -4 },
		clones: { latest: 4, difference: -2 },
	},
	{
		name: 'caesar-cli',
		stars: { latest: 11, difference: 0 },
		forks: { latest: 1, difference: 0 },
		views: { latest: 6, difference: 2 },
		clones: { latest: 9, difference: 3 },
	},
	{
		name: 'cf-detect.now',
		stars: { latest: 3, difference: 0 },
		forks: { latest: 1, difference: 0 },
		views: { latest: 3, difference: 3 },
		clones: { latest: 0, difference: -2 },
	},
	{
		name: 'cloudflare-detect',
		stars: { latest: 11, difference: 1 },
		forks: { latest: 3, difference: 0 },
		views: { latest: 1, difference: -3 },
		clones: { latest: 2, difference: 0 },
	},
	{
		name: 'cryptaddress-validator',
		stars: { latest: 71, difference: 0 },
		forks: { latest: 6, difference: 1 },
		views: { latest: 5, difference: -4 },
		clones: { latest: 3, difference: -1 },
	},
	{
		name: 'cryptaddress.now',
		stars: { latest: 15, difference: 0 },
		forks: { latest: 3, difference: 0 },
		views: { latest: 7, difference: 2 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'cryptocurrency-address-detector',
		stars: { latest: 23, difference: 0 },
		forks: { latest: 2, difference: 0 },
		views: { latest: 0, difference: -2 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'dash-regex',
		stars: { latest: 3, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 3, difference: 1 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'dcipher',
		stars: { latest: 87, difference: 0 },
		forks: { latest: 22, difference: 0 },
		views: { latest: 7, difference: 1 },
		clones: { latest: 2, difference: 2 },
	},
	{
		name: 'dcipher-cli',
		stars: { latest: 164, difference: 4 },
		forks: { latest: 21, difference: 0 },
		views: { latest: 17, difference: 3 },
		clones: { latest: 3, difference: -2 },
	},
	{
		name: 'dogecoin-regex',
		stars: { latest: 4, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 1, difference: 0 },
		clones: { latest: 0, difference: -1 },
	},
	{
		name: 'donations',
		stars: { latest: 51, difference: 0 },
		forks: { latest: 18, difference: 0 },
		views: { latest: 13, difference: -2 },
		clones: { latest: 0, difference: -2 },
	},
	{
		name: 'dymerge',
		stars: { latest: 155, difference: 0 },
		forks: { latest: 40, difference: 0 },
		views: { latest: 32, difference: 3 },
		clones: { latest: 4, difference: 2 },
	},
	{
		name: 'esolangs',
		stars: { latest: 6, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'esolangs-cli',
		stars: { latest: 0, difference: 0 },
		forks: { latest: 1, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'ethereum-regex',
		stars: { latest: 11, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 3, difference: -4 },
		clones: { latest: 1, difference: 1 },
	},
	{
		name: 'ghost-detect',
		stars: { latest: 4, difference: 0 },
		forks: { latest: 1, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 1, difference: 0 },
	},
	{
		name: 'ghost-detect.now',
		stars: { latest: 2, difference: 0 },
		forks: { latest: 2, difference: 0 },
		views: { latest: 0, difference: -2 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'ghost-version',
		stars: { latest: 2, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 0, difference: -1 },
		clones: { latest: 0, difference: -1 },
	},
	{
		name: 'hash-detector',
		stars: { latest: 7, difference: 0 },
		forks: { latest: 3, difference: 0 },
		views: { latest: 0, difference: -3 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'hash-detector-cli',
		stars: { latest: 5, difference: 0 },
		forks: { latest: 3, difference: 0 },
		views: { latest: 2, difference: 1 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'hash-length-regex',
		stars: { latest: 3, difference: 0 },
		forks: { latest: 1, difference: 0 },
		views: { latest: 0, difference: -1 },
		clones: { latest: 0, difference: -1 },
	},
	{
		name: 'hex-cli',
		stars: { latest: 6, difference: 0 },
		forks: { latest: 3, difference: 0 },
		views: { latest: 2, difference: 1 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'instaprof-site',
		stars: { latest: 3, difference: 0 },
		forks: { latest: 1, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'isitup.now',
		stars: { latest: 12, difference: 0 },
		forks: { latest: 3, difference: 0 },
		views: { latest: 0, difference: -3 },
		clones: { latest: 1, difference: -1 },
	},
	{
		name: 'kickthemout',
		stars: { latest: 1621, difference: 0 },
		forks: { latest: 372, difference: 0 },
		views: { latest: 149, difference: 14 },
		clones: { latest: 32, difference: 5 },
	},
	{
		name: 'lexis-cli',
		stars: { latest: 3, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 0, difference: -1 },
	},
	{
		name: 'lexis-count',
		stars: { latest: 2, difference: 0 },
		forks: { latest: 1, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'lexis.now',
		stars: { latest: 2, difference: 0 },
		forks: { latest: 2, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'litecoin-regex',
		stars: { latest: 4, difference: 0 },
		forks: { latest: 1, difference: 0 },
		views: { latest: 5, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'md5-regex',
		stars: { latest: 4, difference: 0 },
		forks: { latest: 1, difference: 0 },
		views: { latest: 2, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'monero-regex',
		stars: { latest: 5, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 1, difference: 0 },
	},
	{
		name: 'movies-for-hackers',
		stars: { latest: 7974, difference: 0 },
		forks: { latest: 740, difference: 0 },
		views: { latest: 471, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'neo-regex',
		stars: { latest: 2, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 5, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'now-name',
		stars: { latest: 0, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'now-name-cli',
		stars: { latest: 0, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'onioff',
		stars: { latest: 384, difference: 0 },
		forks: { latest: 100, difference: 0 },
		views: { latest: 21, difference: -3 },
		clones: { latest: 8, difference: 4 },
	},
	{
		name: 'onion-regex',
		stars: { latest: 8, difference: 0 },
		forks: { latest: 4, difference: 0 },
		views: { latest: 3, difference: 0 },
		clones: { latest: 1, difference: 0 },
	},
	{
		name: 'open-anyway',
		stars: { latest: 5, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'open-anyway-cli',
		stars: { latest: 4, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'ripemd-regex',
		stars: { latest: 2, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'ripple-regex',
		stars: { latest: 3, difference: 0 },
		forks: { latest: 0, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'sha-regex',
		stars: { latest: 4, difference: 0 },
		forks: { latest: 1, difference: 0 },
		views: { latest: 18, difference: 4 },
		clones: { latest: 1, difference: 0 },
	},
	{
		name: 'terminals-are-sexy',
		stars: { latest: 8898, difference: 28 },
		forks: { latest: 484, difference: 10 },
		views: { latest: 623, difference: 84 },
		clones: { latest: 2, difference: -2 },
	},
	{
		name: 'tor-detect',
		stars: { latest: 12, difference: 0 },
		forks: { latest: 3, difference: 0 },
		views: { latest: 0, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'tor-detect.now',
		stars: { latest: 5, difference: 0 },
		forks: { latest: 3, difference: 1 },
		views: { latest: 1, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
	{
		name: 'url-cli',
		stars: { latest: 3, difference: 0 },
		forks: { latest: 4, difference: 1 },
		views: { latest: 4, difference: 0 },
		clones: { latest: 0, difference: 0 },
	},
];
